# Generated by Django 4.1.5 on 2023-01-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_records',
            name='date',
            field=models.DateField(),
        ),
    ]
